# EchoSwift Configuration

# Output directory for benchmark results
out_dir: "test_results"

# Base URL for the LLM endpoint
base_url: "http://10.216.178.15:8000/v1/completions"

# LLM provider (TGI, Ollama, vLLM, Llamacpp)
provider: "vLLM"

# Model name (required for Ollama and vLLM)
model: "meta-llama/Meta-Llama-3-8B"

# Benchmark parameters
max_requests: 5
user_counts: [3]
input_tokens: [32]
output_tokens: [256]