name: EchoSwift CI/CD

on:
  push:
    branches: [ akhil ]
  pull_request:
    branches: [ akhil ]
  release:
    types: [created, published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: akhil
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    - name: Install package
      run: |
        pip install -e .
    - name: Verify package structure
      run: |
        python -c "import echoswift; import echoswift.utils; print('Package structure verified')"
    - name: List directory contents
      run: |
        pwd
        ls -R
    - name: Run tests
      run: |
        pip list
        python --version
        pytest -v --tb=short

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: akhil
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*